---
- hosts: all
  become: True
  gather_facts: False
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
    - name: Gathering facts
      setup:
  roles:
      - setup



